// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvIJaeyY29C6JJfInZPvlziLBVc4Qourc',
    appId: '1:704596934747:web:059f1d3d737a29da52bf7e',
    messagingSenderId: '704596934747',
    projectId: 'fir-auth-flutter-4aa75',
    authDomain: 'fir-auth-flutter-4aa75.firebaseapp.com',
    storageBucket: 'fir-auth-flutter-4aa75.firebasestorage.app',
    measurementId: 'G-D5HDYHGLMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNeXgMIbZnMFfP4P3qEp62v64DhFrITHA',
    appId: '1:704596934747:android:938c4688763839ab52bf7e',
    messagingSenderId: '704596934747',
    projectId: 'fir-auth-flutter-4aa75',
    storageBucket: 'fir-auth-flutter-4aa75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJOrLAqfKqyQHXcPKr0AEQJkHpCIov-zY',
    appId: '1:704596934747:ios:eba6f845d8686a0052bf7e',
    messagingSenderId: '704596934747',
    projectId: 'fir-auth-flutter-4aa75',
    storageBucket: 'fir-auth-flutter-4aa75.firebasestorage.app',
    androidClientId: '704596934747-12f0fp5d0bjhp1bfimab2osn9hl7bco0.apps.googleusercontent.com',
    iosClientId: '704596934747-hj7b40hbh4urullt9bk5djsj1s5g42c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeDb',
  );
}
